apiVersion: v1
kind: Pod
metadata:
  name: configmap-pod-demo
spec:
  containers:
    - name: configmap-test
      image: busybox:1.28.4
      command:
        - sleep
        - "360000"
      env:
        # 这里是在pod的env里面显示的名字
        - name: DEMO_VAR_AAA
          valueFrom:
            configMapKeyRef:
              name: configmap-demo
              key: aaa
        - name: DEMO_VAR_BBB
          valueFrom:
            configMapKeyRef:
              name: configmap-demo
              key: bbb
  restartPolicy: Never
