apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-config-map
data:
  # 变量在这里
  aaa: this is aaa var
  bbb: this is var bbb

---
apiVersion: v1
kind: Pod
metadata:
  name: configmap-test-pod
spec:
  containers:
    - name: configmap-test
      image: busybox
      command:
        - sleep
        - "360000"
      env:
        # 这里是在pod的env里面显示的名字
        - name: DEMO_VAR_AAA
          valueFrom:
            configMapKeyRef:
              name: demo-config-map
              key: aaa
        - name: DEMO_VAR_BBB
          valueFrom:
            configMapKeyRef:
              name: demo-config-map
              key: bbb
  restartPolicy: Never
