# 副本为3的StatefulSet，serviceName名为nginx
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
  namespace: test
spec:
  selector:
    matchLabels:
      app: nginx
  serviceName: "nginx"
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
              name: web
          volumeMounts:
            - name: www
              mountPath: /usr/share/nginx/html
  # volumeClainTemplate作用：
  # 当在使用statefulset创建pod时，会自动生成一个PVC，从而请求绑定一个PV，从而有自己专用的存储卷。
  volumeClaimTemplates:
    - metadata:
        name: www
        annotations:
          # 这里是 storage class 的 name
          volume.beta.kubernetes.io/storage-class: "mynfs-class"
      spec:
        accessModes: ["ReadWriteOnce"]
        # storageClassName: slow
        resources:
          requests:
            storage: 1Gi
