apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mynfs-class
# 自定义的 provisioner
# Deployment 里面的 PROVISIONER_NAME 字段值
provisioner: mynfs-provisioner
parameters:
  # 如果不指定路径，出来的就是随机路径
  pathPattern: "${.PVC.namespace}/${.PVC.name}"
