# 用于网络和端口测试
# busybox版本最高1.28.4，否则 nslookup 会出问题
apiVersion: v1
kind: Pod
metadata:
  name: busybox
  labels:
    name: busybox
spec:
  containers:
    - name: busybox
      image: busybox:1.28.4
      command:
        - sleep
        - "360000"
