apiVersion: v1
kind: Pod
metadata:
  name: nfs-pod
spec:
  volumes:
    # 暴露出来的，和 containers 的 volumeMounts 对应
    - name: volume1
      persistentVolumeClaim:
        # 和 pvc 里面的一致
        claimName: demo-pvc
  containers:
    - name: demo-container
      image: busybox:1.28.4
      # imagePullPolicy: IfNotPresent
      command:
        - sleep
        - "360000"
      # 下面这个对应docker版的nfs服务器里面的--privileged参数
      securityContext:
        privileged: true
      volumeMounts:
        # 这里的 volume1 对应 demo-pvc里面的
        - name: volume1
          mountPath: "/mydata"
