kind: Service
apiVersion: v1
metadata:
  name: ddd

spec:
  selector:
    # 定义此 service 关联的 pod 对应的标签
    app: demo1
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  clusterIP: None
  type: ClusterIP
