apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      # 定义 Deployment 关联的 Pod 的标签
      app: demo1
  replicas: 3
  template:
    # Pod的模板
    metadata:
      labels:
        # Pod的标签
        app: demo1
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
