#!/usr/bin/env python
# -*- coding: UTF-8 -*-

from __future__ import print_function

import os

from py_mods import proc

def get_image_list():
    print("try to get image list from k8s.gcr.io")

    image_list = []
    results= proc.exec_cmd_with_result_list("kubeadm config images list")
    for result in results:
        info = str(result, 'utf-8')
        if info.find("k8s.gcr.io/") != -1:
            image_list.append(info.strip('\n'))
    print(image_list)
    return image_list

def run_tag_pull(image_list):
    print("try to pull images:")
    for real_image in image_list:
        mirror_image = real_image.replace("k8s.gcr.io", "registry.cn-hangzhou.aliyuncs.com/google_containers")
        cmd = "./docker_tag_pull %s %s" % (real_image, mirror_image)
        os.system(cmd)

def run_kube_init():
    os.system("kubeadm init")

if __name__ == "__main__":
    image_list = get_image_list()
    run_tag_pull(image_list)