apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-httpd
spec:
  selector:
    matchLabels:
      run: my-httpd
  replicas: 3
  template:
    metadata:
      labels:
        run: my-httpd
    spec:
      containers:
        - name: my-httpd
          image: httpd
          ports:
            - containerPort: 80
