# 需要单独启动nginx的service
apiVersion: v1
kind: Service
metadata:
  # k8s集群内部可以通过域名访问
  name: nginx-service-nodeport
spec:
  selector:
      app: nginx
  ports:
    - name: http
      port: 8000
      protocol: TCP
      targetPort: 80
    - name: https
      port: 8443
      protocol: TCP
      targetPort: 443
  type: NodePort