apiVersion: v1
kind: Service
metadata:
  # k8s集群内部可以通过域名访问, 和 deployment一致的话，kuboard能识别出来
  # name: nginx-service
  name: my-httpd
spec:
  type: NodePort
  selector:
    run: my-httpd
  ports:
    - name: http
      port: 8000
      protocol: TCP
      targetPort: 80
      nodePort: 32500