apiVersion: v1
kind: Service
metadata:
  # k8s集群内部可以通过域名访问
  name: nginx-service
spec:
  type: NodePort
  selector:
    run: my-httpd
  ports:
    - name: http
      port: 8000
      protocol: TCP
      targetPort: 80
      nodePort: 32500
