apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo-pvc
spec:
  accessModes:
    - ReadWriteMany
  # 定义具体绑定到哪个pv
  volumeName: demo-pv-read-write-many
  # storageClassName: nfs
  resources:
    requests:
      storage: 1Gi
