apiVersion: v1
kind: PersistentVolume
metadata:
  name: demo-pv-read-only-many
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadOnlyMany
  nfs:
    path: "/nfs/pv_read_only_many"
    server: 192.168.88.126
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: demo-pv-read-write-many
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    # 目录需要提前创建好，否则会报错
    # 多个客户端读写
    path: "/nfs/pv_read_write_many"
    server: 192.168.88.126
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: demo-pv-read-write-once
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: "/nfs/pv_read_write_once"
    server: 192.168.88.126
