apiVersion: v1
kind: Pod
metadata:
  name: nfs-pod
spec:
  volumes:
    - name: volume1
      persistentVolumeClaim:
        claimName: pvc001
  containers:
    - name: my-container1
      image: busybox
      imagePullPolicy: IfNotPresent
      args:
        - /bin/sh
        - -c
        - sleep 30000
      # 下面这个对应docker版的nfs服务器里面的--privileged参数
      securityContext:
        privileged: true
      volumeMounts:
        - name: volume1
          mountPath: "/mydata"